### ISSUE TITLE
/api/admin/plugins/jwt not found

### ISSUE THREAD

**Issue by misterch0c** [bsparks/nodebb-plugin-jwt#1]
![img](http://i.imgur.com/cpusBOU.png)
I've tried installing it with npm and from the nodebb dashboard. Also tried sudo npm and I'm admin

<pre>
5/8 21:16 [32294] - error: [plugins] Error executing 'static:app.load' in plugin 'nodebb-plugin-jwt'
5/8 21:16 [32294] - error:  TypeError: Cannot read property 'buildHeader' of undefined
    at Object.JWT.init [as method] (/home/unkn0wn/web/nodebb/node_modules/nodebb-plugin-jwt/library.js:25:58)
    at /home/unkn0wn/web/nodebb/src/plugins/hooks.js:133:14
    at /home/unkn0wn/web/nodebb/node_modules/async/lib/async.js:122:13
    at _each (/home/unkn0wn/web/nodebb/node_modules/async/lib/async.js:46:13)
    at Object.async.each (/home/unkn0wn/web/nodebb/node_modules/async/lib/async.js:121:9)
    at fireStaticHook (/home/unkn0wn/web/nodebb/src/plugins/hooks.js:122:9)
    at Object.Plugins.fireHook (/home/unkn0wn/web/nodebb/src/plugins/hooks.js:68:5)
    at Plugins.reloadRoutes (/home/unkn0wn/web/nodebb/src/plugins.js:129:11)
    at /home/unkn0wn/web/nodebb/node_modules/async/lib/async.js:653:23
    at /home/unkn0wn/web/nodebb/node_modules/async/lib/async.js:607:21

</pre>

**Comment by bsparks** [comment]
I actually haven't used nodeBB in a while since this, possibly an updated version changed the API. I think perhaps one of the forks has updated this? PR is welcome, otherwise it may be some time before I can look deeply into it myself, sorry.
